WEBKIT_OPTION_BEGIN()
#set(PROJECT_VERSION_MAJOR 0)
#set(PROJECT_VERSION_MINOR 1)
#set(PROJECT_VERSION_PATCH 0)
#set(PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH})

#set(DATA_DIR ${CMAKE_INSTALL_PREFIX}/share/${PROJECT_NAME}-${PROJECT_VERSION})


#add_definitions(-DDATA_DIR="${DATA_DIR}")

#add_definitions(-DWEBCORE_NAVIGATOR_VENDOR="Appcelerator Inc.")
add_definitions(-DBUILDING_ANDROID__=1)
#add_definitions(-DBUILD_WEBKIT)

list(APPEND CMAKE_FIND_ROOT_PATH ${CMAKE_SOURCE_DIR}/icu_android)
list(APPEND WEBKIT_LIBRARIES_LINK_DIR ${CMAKE_SOURCE_DIR}/icu_android/prebuilt/${ANDROID_ABI})

find_package(ICU REQUIRED)
set(WTF_USE_ICU_UNICODE 1)

